spring:
  application:
    name: sample
  config:
    use-legacy-processing: true
  profiles:
    active: local
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080
---
spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sample
    username: josue
    password: globant98
    initialization-mode: always