spring:
  application:
    name: sample
  config:
    use-legacy-processing: true
  server:
    port: 8090
  profiles:
    active: local
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    show-sql: true
---
spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sample
    username: josue
    password: globant98